# Generated by Django 5.0.1 on 2024-02-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_dog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebcamImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='webcam_images/')),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
