# Generated by Django 5.0.1 on 2024-03-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_approvedentry_pendingentry_delete_webcamimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('dog_view_url', models.URLField()),
                ('bill_view_url', models.URLField()),
            ],
        ),
    ]
